<a href="https://colab.research.google.com/github/ReetHabar/AI-ML_Basic_to-_Advance_code_-_theory-s/blob/main/NUMPY_ai_ml_class_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NumPy Class 1 — Practice Questions**

In [ ]:
#1.Numpy Stand for= Numarical Python
#To calculate numarical calculation

In [ ]:
#3.create a 1D array
import numpy as np
var1= [10, 20, 30, 40]
print(np.array(var1))

[10 20 30 40]


In [ ]:
#4.create a 2x3 array
import numpy as np
var_1=([[0,0,0],
             [0,0,0]])
print(np.array(var_1))
#another way
var_2=np.zeros((2,3))
print("Zeros matrix(2x3):-\n",var_2)

[[0 0 0]
 [0 0 0]]
Zeros matrix(2x3):-
 [[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#5.create a code of 3x4 matrix
import numpy as np
var_2=np.ones((3,4))
print("Zeros matrix(2x3):-\n",var_2)

#6.What is the output of np.arange(5)?
print("\n",np.arange(5))
  #0 to 4

#7.What is the output of np.arange(0, 10, 2)?
print("\n",np.arange(0, 10, 2))
  #([0, 2, 4, 6, 8])

#8.What is the output of np.arange(5, 3, -0.5)?
print("Arrange of size:-\n",np.arange(5, 3, -0.5))
  #([5. , 4.5, 4. , 3.5])

#9.What is the output of np.linspace(0, 1, 5)?
print("linespace of \n",np.linspace(0, 1, 5))
  #([0.  , 0.25, 0.5 , 0.75, 1.  ])
  #Theory

# 10.What is the key difference between np.arange() and np.linspace()?
#    A) arange uses floats; linspace uses integers
# >>B) arange takes a step size; linspace takes a number of samples
#    C) They are identical in behavior
#    D) arange is slower


Zeros matrix(2x3):-
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

 [0 1 2 3 4]

 [0 2 4 6 8]
Arrange of size:-
 [5.  4.5 4.  3.5]
linespace of 
 [0.   0.25 0.5  0.75 1.  ]
shape of array:-
 (2, 3)
number of dimensions of the array:-
 2
size of array:-
 6
Data Type:-
 int64


**Section 2: Array Attributes & Reshaping**

In [ ]:
import numpy as np

#11.Given a = np.array([[1,2,3],[4,5,6]]), what is a.shape?
a = np.array([[1,2,3],[4,5,6]])
print("shape of array:-\n",a.shape)
  #(2, 3)

#12.For the same array above, what is a.ndim?
print("number of dimensions of the array:-\n",a.ndim)#number of dimensions of the array
  #2

#13.For the same array above, what is a.size?
print("size of array:-\n",a.size)
  #6

#14. For the same array above, what is a.dtype?
print("Data Type:-\n",a.dtype)
  #int6

# 15. Why is .dtype important for deep learning frameworks like PyTorch or TensorFlow?
#    A) It controls the color of output
# >>B) Consistent data types are crucial for performance and compatibility
#    C) It speeds up Python loops
#    D) It determines the number of axes

#16.Create a 1D array of 12 elements (0–11) and reshape it into a 3×4 matrix.
import numpy as np
a=(np.arange(12))
print(a)
print("reshape a array into 3x4 matrix:-\n",(a.reshape(3,4)))
print("\n")

#17.Reshape np.arange(12) into a 3D tensor of shape (2, 2, 3).
tensor_3d = a.reshape(2, 2, 3)#2x2x3 matrix [3D]
print(f'\nReshaped to (2, 2, 3):\n{tensor_3d}')
print("\n")

#18.Given only shape = arr.shape, compute the equivalent of arr.size and arr.ndim without using those attributes directly.


#19.Create a 1D array of 25 random values (0–100, rounded to 2 decimals) and reshape it into a 5×5 matrix.
a=np.random.uniform(0,100,25)
print("Random uniform:-\n",a)
print("\n")

print("Rounded to 2 decimal:-\n",np.round(a, 2))
print("\n")

print("array reshape:\n",a.reshape(5,5))

#20.In ML, why is .reshape() important when working with image data?
#reshape() is important because machine learning models require data in a specific shape or format.


shape of array:-
 (2, 3)
number of dimensions of the array:-
 2
size of array:-
 6
Data Type:-
 int64
[ 0  1  2  3  4  5  6  7  8  9 10 11]
reshape a array into 3x4 matrix:-
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]



Reshaped to (2, 2, 3):
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


Random uniform:-
 [36.72857667 94.30358376 48.96597998 25.63580983 27.4596759  13.27841375
 48.2842307   4.42210652 97.04763498 75.99378123 57.96091178 29.78585524
 87.32928511 93.27639173 36.67487905 91.27338211 17.81984076 80.33658005
 89.76290214 58.80282793 77.50729227 54.15240179 57.16244207 24.4460066
 88.95099258]


Rounded to 2 decimal:-
 [36.73 94.3  48.97 25.64 27.46 13.28 48.28  4.42 97.05 75.99 57.96 29.79
 87.33 93.28 36.67 91.27 17.82 80.34 89.76 58.8  77.51 54.15 57.16 24.45
 88.95]


array reshape:
 [[36.72857667 94.30358376 48.96597998 25.63580983 27.4596759 ]
 [13.27841375 48.2842307   4.42210652 97.04763498 75.99378123]
 [57.96091178 29.78585524 87.32928511 93.2763917

**Section 3: Indexing & Slicing**

In [ ]:
import numpy as np
#21.Given data = np.arange(8), what is data[2:7]?
data = np.arange(8)
print(data)
print("\n")
print("Data [2:7] is:\n",data[2:7])
#The data[2:7] is [2 3 4 5 6]
print("\n")

#22.Given m = np.arange(8).reshape(2,4), what is m[1, 2]?
m = np.arange(8)#0,1,2,3,4,5,6,7
re_sp=m.reshape(2,4)#[0,1,2,3],[4,5,6,7]

p=re_sp[1, 2]
#[row(index from 0),column(index from 0)]
#[0,1,2,3]
#[7,5,6,4](here come 1 no row)
# 0 1 2 3---index position (then come 2 no column index from 0)= 6 value
print("reshape:\n",re_sp)
print("\n")
print("m[1, 2] is:\n",p)
print(" \n")
#m[1,2] is 6

#23.Given the same m, what is m[:, :3]?
m = np.arange(8).reshape(2,4)
print("m[:, :3] is:\n",m[:, :3])
print("\n")
#[[0 1 2]
 # [4 5 6]]

#24.Given data = np.arange(8), what does data > 5 produce?
data = np.arange(8)
print(data)
mask=data>5
print(mask)
print("\n")

#25.What is the result of data[data > 5] if data = np.arange(8)
data = np.arange(8)
a= data[data > 5]
print("The value of data[data > 5]\n:",a)#means all value greater than 5
print("\n")

#26 Given a 4×4 matrix called matrix, use np.ix_ to select rows 1, 2, 3 and columns 0, 2, 3.
a= np.arange(16).reshape(4,4)
result =a[np.ix_([1,2,3], [0,2,3])]
print("Output is:\n",result)

[0 1 2 3 4 5 6 7]


Data [2:7] is:
 [2 3 4 5 6]


reshape:
 [[0 1 2 3]
 [4 5 6 7]]


m[1, 2] is:
 6
 

m[:, :3] is:
 [[0 1 2]
 [4 5 6]]


[0 1 2 3 4 5 6 7]
[False False False False False False  True  True]


The value of data[data > 5]
: [6 7]


[[ 4  6  7]
 [ 8 10 11]
 [12 14 15]]
